const strings = {
  searchPattern: "Cerca i modelli",
  pressFocus: "Premi '/' per spostare il focus",
  title: "Generatore di modelli SVG",
  heading: "<span>Modelli SVG</span> personalizzabili per i tuoi progetti",
  keywords: "modelli svg, modelli, sfondi svg, sfondi vettoriali, generatore di modelli, creatore di modelli",
  patterns: "modelli",
  license: "Licenza MIT",
  free: "Gratuito",
  description: "Un semplice generatore di pattern online per creare modelli SVG ripetibili.",
  description2: "Velocizza il tuo sito web senza compromettere la qualità delle immagini.",
  description3: "Perfetto per sfondi di siti web, abbigliamento, branding, packaging design e altro ancora.",
  filter: "Filtro",
  sort: "Ordina",
  filterMode: "Filtra per Modalità",
  filterColors: "Filtra per Colore",
  allModes: "Tutte le Modalità",
  stroke: "Bordo",
  fill: "Riempimento",
  allColors: "Tutti i colori",
  colors: "colori",
  latest: "Più recente",
  oldest: "Meno recente",
  alphabetical: "Alfabetico",
  updateDate: "Data di aggiornamento",
  changeTheme: "Cambia Tema",
  changelog: "Registro modifiche",
  features: "Funzionalità",
  downloads: "Download",
  translate: "Traduci",
  privacy: "Informativa sulla privacy",
  privacyFull: "Questa app non raccoglie ne conserva nessun dato dell'utente",
  signUp: "Iscriviti per gli aggiornamenti del progetto e ottenere modelli gratuiti consegnati mensilmente alla tua casella di posta in arrivo",
  email: "Il tuo indirizzo email",
  sendPatterns: "Inviami i modelli",
  zoom: "Zoom",
  hSpacing: "Spaziatura orizzontale",
  vSpacing: "Spaziatura verticale",
  hPosition: "Posizione orizzontale",
  vPosition: "Posizione verticale",
  angle: "Angolo",
  inspire: "Ispirami",
  random: "Motivo Casuale",
  reset: "Reset",
  copy: "Copia",
  copyCSS: "Copia CSS",
  copySVG: "Copia SVG",
  download: "Scarica",
  downloadSVG: "Scarica come file SVG",
  downloadPNG: "Scarica come file PNG",
  dimensions: "Dimensioni",
  width: "Larghezza",
  height: "Altezza",
  hide: "Nascondi UI",
  lock: "Blocca",
  unlock: "Sblocca",
  checkOut: "Se ti piace creare modelli SVG e sfondi, dovresti guardare questo.",
  generate: "Genera gratuitamente modelli SVG completamente personalizzabili.",
  patternsCount: "200+ modelli disponibili su https://pattern.monster",
  square: "Quadrato",
  rounded: "Arrotondato",
  join: "Modalità Unione",
  tweet: "Condividi il tuo tweet",
  waves: "Onde",
  chevron: "Chevron",
  straightLines: "Linee rette",
  crossSection: "Sezione trasversale",
  brickWall: "Parete di Mattoni",
  herringbone: "Herringbone",
  flower: "Fiori",
  plus: "Croci",
  circles: "Cerchi",
  concentricCircles: "Cerchi Concentrici",
  adjointedCircles: "Cerchi Aggiuntivi",
  adjointedDiamonds: "Diamanti Aggiunti",
  diamonds: "Diamanti",
  hexagon: "Esagoni",
  overlappingHexagons: "Esagoni Sovrapposti",
  squaresSquares: "Quadrati & Quadrati",
  squaresDiamonds: "Quadrati & Diamanti",
  squaresCircles: "Quadrati & Cerchi",
  squaresPlus: "Quadrati & altro",
  squaresStars: "Quadrati & Stelle",
  starsLines: "Stelle & Linee",
  triangles: "Triangoli",
  invertedTriangles: "Triangoli Invertiti",
  checkerboard: "Scacchiera",
  japanesePattern: "Modello Giapponese",
  eyes: "Occhi",
  jigsaw: "Mosaico",
  railroad: "Binari",
  octagons: "Ottagoni",
  lines: "Linee",
  scales: "Scale",
  leaves: "Foglie",
  pipes: "Tubi",
  zebra: "Zebra",
  memphis: "Modello Memphis",
  greekKey: "Greca",
  chinese: "Modello Cinese",
  newPattern: "Nuovo Modello",
  doubleBubble: "Doppia Bolla",
  stars: "Stelle",
  semicircles: "Semicerchi",
  songket: "Modelli di Songket",
  cubes: "Cubi",
  stainedGlass: "Vetro colorato",
  tiles: "Piastrelle",
  rectanglesSquares: "Rettangoli & Quadrati",
  mexicanPattern: "Modello Messicano",
  ethnicPattern: "Modello Etnico",
  plaidPattern: "Modello Plaid",
  doodlePattern: "Modello Doodle",
  batikPattern: "Modello Batik",
  curves: "Curve",
  rhombus: "Rombo",
  stripes: "Striscie",
  squares: "Quadrati",
  clouds: "Nuvole",
  africanPattern: "Modello Africano",
  arabicPattern: "Modello Arabo",
  abstractPattern: "Modello Astratto",
  geometricPattern: "Modello Geometrico",
  tribalPattern: "Modello Tribale",
};
export default { strings };
